server:
  port: 8038
# SpringBoot整合MyBatis框架

# 1.加载MyBatis配置文件
mybatis:
  #  扫描classpath下mapper目录下的所有.xml文件
  mapper-locations: classpath:mapper/*.xml
  #  实体类的包路径
  type-aliases-package: com.ddcx.springboot.demodatabase.entity
# 2.数据库配置:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver